format = """
$time$username$sudo[@](cyan)$hostname$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$terraform\
$golang\
$python\
${custom.ansible}\
$cmd_duration\
$azure\n$kubernetes\n$character
"""

add_newline = false
command_timeout = 2000

[username]
style_user = "fg:2"
style_root = "red bold"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
format = "[$hostname](cyan) "

[directory]
truncation_length = 0
style = "cyan"

[character]
success_symbol = "[â””â”€â–¶ \\$](fg:2) "
error_symbol = "[â””â”€â–¶ \\$](red) "

[terraform]
format = "\\(tf-ws [$symbol$workspace]($style)\\) "

[time]
disabled = true
format = "ðŸ•™ [$time]($style) "
style = "fg:11"

[sudo]
disabled = true
format = "[ as $symbol]($style)"
style = "white"

[azure]
disabled = false
symbol = "â˜ï¸ "
format = "[\n[â”œ](fg:2) $symbol($subscription) ]($style)"
style = "blue"

[kubernetes]
symbol = "â˜¸"
disabled = false
format = '[â”œ](fg:2) [$symbol$context( \($namespace\)) ]($style)'

[custom.ansible]
disabled = false
symbol = 'ó±‚š'
description = 'Ansible Core version'
detect_files = ['ansible.cfg']
style = 'red'
format = 'via [$symbol]($style) [$output]($style bold) '
shell = '/bin/bash'
command = 'echo -n $(ansible --version 2>/dev/null | perl -nle "print $1 if /core (\d+\.\d+\.\d+)/")'

[golang]
symbol = 'î˜§'
style = 'fg:#00ADD8'
format = 'via [$symbol]($style) [$version]($style bold) '

[python]
symbol = 'îœ¼'
style = 'yellow'
format = 'via [$symbol]($style) [$version]($style bold) '
